// Ed25519 public keys used to verify license tokens, keyed by `kid`. These are
// compiled into out/main and protected at rest by asar integrity + the OS code
// signature (see electron-builder.yml + scripts/after-pack.cjs). The private
// key lives ONLY in the web app's server env.
//
// To rotate: generate a new pair (apps/web/scripts/generate-license-keys.mjs),
// add the new public key here under its kid, deploy, then retire the old kid.
//
// Generated by apps/web/scripts/setup-dev.mjs.
export const LICENSE_PUBLIC_KEYS: Record<string, string> = {
	'lk_bbf4174a': `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAqWoYAUhkJ2/xRwMuYyLi7wYrZN/ZoUbgcX5oOyW27cM=
-----END PUBLIC KEY-----`
};
