import { v } from 'convex/values';
import { mutation, secretMutation } from './utils';
import { authComponent } from './auth';
import { getOrCreateLicense, startTrialIfEligible } from './licenses';
import { hasBetaAccess } from './waitlist';
import { evaluateLicense, activeSinceFor } from './licensingShared';
import { rateLimiter } from './rateLimiter';
import { convexError, createConvexError } from './errors';
import type { Doc } from './_generated/dataModel';
import type { QueryCtx } from './_generated/server';

// How long a device code is valid to poll before the user must restart.
const CODE_TTL_MS = 10 * 60 * 1000;

const fingerprintSource = v.union(v.literal('os'), v.literal('fallback'));

/** Non-expired, non-consumed rows only (denied rows stay lookup-able so the
 * desktop can learn it was rejected). */
function isLive(code: Doc<'activationCodes'>, now: number): boolean {
	return code.expiresAt > now && !code.consumedAt;
}

/**
 * Called by POST /api/activation/start (secret-authed; the desktop has no
 * session yet). Records a pending device-authorization code pair. The raw
 * codes are generated by SvelteKit; Convex only sees their hashes. Throws
 * ActivationCodeCollision if the (astronomically unlikely) user code is already
 * pending, so SvelteKit can regenerate.
 */
export const start = secretMutation({
	args: {
		userCodeHash: v.string(),
		deviceCodeHash: v.string(),
		fingerprint: v.string(),
		fingerprintSource,
		machineName: v.optional(v.string()),
		platform: v.optional(v.string()),
		appVersion: v.optional(v.string()),
		ipHash: v.optional(v.string())
	},
	handler: async (ctx, args) => {
		if (args.ipHash) {
			const ip = await rateLimiter.limit(ctx, 'activationStart', { key: args.ipHash });
			if (!ip.ok) throw createConvexError(convexError.RateLimited());
		}

		const now = Date.now();
		const existing = await ctx.db
			.query('activationCodes')
			.withIndex('by_userCodeHash', (q) => q.eq('userCodeHash', args.userCodeHash))
			.collect();
		if (existing.some((c) => isLive(c, now))) {
			throw createConvexError(convexError.ActivationCodeCollision());
		}

		await ctx.db.insert('activationCodes', {
			userCodeHash: args.userCodeHash,
			deviceCodeHash: args.deviceCodeHash,
			fingerprint: args.fingerprint,
			fingerprintSource: args.fingerprintSource,
			machineName: args.machineName,
			platform: args.platform,
			appVersion: args.appVersion,
			createdAt: now,
			expiresAt: now + CODE_TTL_MS
		});

		return { expiresAt: now + CODE_TTL_MS };
	}
});

/**
 * Called from the /activate page (with the user's session) once they type a
 * user code, to show what they are about to authorize. The browser sends the
 * SHA-256 hash of the normalized code, so Convex never sees the raw code.
 */
export const inspect = mutation({
	args: { userCodeHash: v.string() },
	handler: async (ctx, args) => {
		const user = await authComponent.getAuthUser(ctx);
		if (!user) throw createConvexError(convexError.Unauthorized());

		const attempt = await rateLimiter.limit(ctx, 'activationInspect', { key: user._id });
		if (!attempt.ok) throw createConvexError(convexError.RateLimited());

		const code = await lookupByUserCode(ctx, args.userCodeHash);
		const now = Date.now();
		if (!code || !isLive(code, now) || code.deniedAt) {
			return { valid: false as const };
		}
		return {
			valid: true as const,
			machineName: code.machineName ?? null,
			platform: code.platform ?? null,
			alreadyApproved: !!code.approvedAt
		};
	}
});

/** Approve a pending device code for the signed-in user. */
export const approve = mutation({
	args: { userCodeHash: v.string() },
	handler: async (ctx, args) => {
		const user = await authComponent.getAuthUser(ctx);
		if (!user) throw createConvexError(convexError.Unauthorized());

		const rl = await rateLimiter.limit(ctx, 'activationApprove', { key: user._id });
		if (!rl.ok) throw createConvexError(convexError.RateLimited());

		const code = await lookupByUserCode(ctx, args.userCodeHash);
		const now = Date.now();
		if (!code || !isLive(code, now) || code.deniedAt) {
			throw createConvexError(convexError.InvalidActivationCode());
		}

		// Ensure the license row exists so the first poll is licensed.
		await getOrCreateLicense(ctx, user._id);

		await ctx.db.patch(code._id, { userId: user._id, approvedAt: now });
		return { ok: true as const };
	}
});

/** Reject a pending device code. */
export const deny = mutation({
	args: { userCodeHash: v.string() },
	handler: async (ctx, args) => {
		const user = await authComponent.getAuthUser(ctx);
		if (!user) throw createConvexError(convexError.Unauthorized());

		const code = await lookupByUserCode(ctx, args.userCodeHash);
		const now = Date.now();
		if (code && isLive(code, now) && !code.deniedAt) {
			await ctx.db.patch(code._id, { deniedAt: now });
		}
		return { ok: true as const };
	}
});

/**
 * Called by POST /api/activation/poll (secret-authed). Reports the flow status
 * and, once approved, consumes the code: registers the device, starts the
 * trial on first-ever activation, and stores the device token hash. Returns the
 * license decision for SvelteKit to sign; the raw device token is generated by
 * SvelteKit, not here.
 */
export const poll = secretMutation({
	args: {
		deviceCodeHash: v.string(),
		tokenHash: v.string(),
		fingerprint: v.string(),
		fingerprintSource,
		platform: v.string(),
		appVersion: v.string(),
		machineName: v.optional(v.string()),
		ipHash: v.optional(v.string())
	},
	handler: async (ctx, args) => {
		if (args.ipHash) {
			const ip = await rateLimiter.limit(ctx, 'activationPoll', { key: args.ipHash });
			if (!ip.ok) throw createConvexError(convexError.RateLimited());
		}
		const perCode = await rateLimiter.limit(ctx, 'activationPollCode', {
			key: args.deviceCodeHash
		});
		if (!perCode.ok) throw createConvexError(convexError.RateLimited());

		const code = await ctx.db
			.query('activationCodes')
			.withIndex('by_deviceCodeHash', (q) => q.eq('deviceCodeHash', args.deviceCodeHash))
			.unique();
		const now = Date.now();

		if (!code || code.consumedAt || code.expiresAt < now) {
			return { status: 'expired' as const };
		}
		if (code.deniedAt) return { status: 'denied' as const };
		if (!code.approvedAt || !code.userId) return { status: 'pending' as const };

		// Bind the token to the machine that started the flow; a mismatch means
		// the device code is being redeemed from somewhere it wasn't issued.
		if (code.fingerprint !== args.fingerprint) {
			await ctx.db.patch(code._id, { consumedAt: now });
			return { status: 'expired' as const };
		}

		await ctx.db.patch(code._id, { consumedAt: now });

		let license = await getOrCreateLicense(ctx, code.userId);

		// Beta gate. Checked *before* the trial starts so a blocked activation
		// doesn't burn the one-per-GitHub-account trial. The device is still
		// registered and still gets its token below, so once the account is
		// accepted the app picks the license up on its next validation instead of
		// needing the whole activation flow again.
		const betaAllowed = await hasBetaAccess(ctx, code.userId);
		if (betaAllowed) license = await startTrialIfEligible(ctx, license);

		let device = await ctx.db
			.query('devices')
			.withIndex('by_license_fingerprint', (q) =>
				q.eq('licenseId', license._id).eq('fingerprint', args.fingerprint)
			)
			.unique();
		if (device) {
			await ctx.db.patch(device._id, {
				lastSeenAt: now,
				platform: args.platform,
				appVersion: args.appVersion,
				fingerprintSource: args.fingerprintSource,
				name: args.machineName ?? device.name,
				revokedAt: undefined
			});
		} else {
			const deviceId = await ctx.db.insert('devices', {
				licenseId: license._id,
				fingerprint: args.fingerprint,
				fingerprintSource: args.fingerprintSource,
				name: args.machineName,
				platform: args.platform,
				appVersion: args.appVersion,
				firstSeenAt: now,
				lastSeenAt: now,
				validationCount: 0
			});
			device = (await ctx.db.get(deviceId))!;
		}

		await ctx.db.insert('deviceTokens', {
			tokenHash: args.tokenHash,
			licenseId: license._id,
			userId: license.userId,
			deviceId: device._id,
			createdAt: now,
			lastUsedAt: now
		});

		const decision = betaAllowed
			? evaluateLicense(
					{
						plan: license.plan,
						status: license.status,
						trialEndsAt: license.trialEndsAt
					},
					now
				)
			: ({ allowed: false, reason: 'waitlist' } as const);

		// See licensing.validateDevice: the holder's display identity travels with
		// the token so the desktop shows the account the license actually belongs to.
		const holderUser = await authComponent.getAnyUserById(ctx, license.userId);
		return {
			status: 'approved' as const,
			decision,
			holder: holderUser
				? {
						name: holderUser.name ?? null,
						email: holderUser.email ?? null,
						image: holderUser.image ?? null
					}
				: null,
			userId: license.userId,
			licenseId: license._id,
			deviceId: device._id,
			plan: license.plan,
			activeSince: activeSinceFor({
				plan: license.plan,
				lifetimePurchasedAt: license.lifetimePurchasedAt
			})
		};
	}
});

async function lookupByUserCode(
	ctx: QueryCtx,
	userCodeHash: string
): Promise<Doc<'activationCodes'> | null> {
	const rows = await ctx.db
		.query('activationCodes')
		.withIndex('by_userCodeHash', (q) => q.eq('userCodeHash', userCodeHash))
		.collect();
	if (rows.length === 0) return null;
	// Prefer the newest live row if the hash was ever reused across TTLs.
	rows.sort((a, b) => b.createdAt - a.createdAt);
	return rows[0];
}
